### ISSUE TITLE
Something wrong when I don't set drafts and auto_category

### ISSUE THREAD

**Issue by ryomahan** [Rozbo/hexo-abbrlink#41]
I used this plugin a long time ago.

But there was an error during my most recent repository code commit.

```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'enable' of undefined
    at Hexo.logic (/Users/ryoma/Documents/write/wiki/node_modules/hexo-abbrlink/lib/logic.js:59:44)
    at Hexo.tryCatcher (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/ryoma/Documents/write/wiki/node_modules/hexo/lib/extend/filter.js:62:52
    at tryCatcher (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ryoma/Documents/write/wiki/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

This BUG wasted two days of my time.

Now I've found out why, but only because I didn't set up options for this plugin!

I don't understand if this is a flaw in Hexo or a flaw in the plug-in, can't the plug-in itself set its own default value when judging, this kind of upgrade will bring trouble to most plug-in users, I hope to be able to fix it.

我很久之前就使用这个插件了，但最近一次我提交仓库代码的过程中出现了错误（如上）。
因为报错不明显，这个 BUG 浪费了我两天的时间去排查，最终才发现是因为我没有给这个插件新增的两个选项设置默认值！

我不明白这是 Hexo 的缺陷还是插件的缺陷，难道插件本身不能在判断的时候自己设置默认值嘛，这种升级会给大部分插件使用者带来困扰，希望能够修改一下。

**Comment by ohroy** [comment]
@KumaNNN can you check it pls ?
