### ISSUE TITLE
travis 持续集成出错

### ISSUE THREAD

**Issue by gustave001** [Rozbo/hexo-abbrlink#44]
出错信息如下，uninstall abbrlink就正常了

INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'enable' of undefined
    at Hexo.logic (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_hexo-abbrlink@2.1.5@hexo-abbrlink/lib/logic.js:59:44)
    at Hexo.tryCatcher (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/method.js:15:34)
    at Promise.each.filter (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_hexo@3.9.0@hexo/lib/extend/filter.js:60:50)
    at tryCatcher (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/travis/build/kikyou93/kikyou93.github.io/node_modules/_bluebird@3.7.2@bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate]

**Comment by KumaNNN** [comment]
Please re install the plug-in or wait for the author to update the version number

**Comment by KumaNNN** [comment]
请重新安装插件或等待作者更新版本号

**Comment by ohroy** [comment]
fixed
